version: "3.7"
services:

  frontend: &frontend
    build:
      context: ./frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/src/app
    depends_on:
      - "backend"

  frontend-dev:
    <<: *frontend
    ports:
      - "4200:4200"
    build:
      context: ./frontend
      dockerfile: Dockerfile-dev

  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testconstant

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
      PMA_ARBITRARY: 1
    ports:
      - 8000:8000
    depends_on:
      - mysql

  backend:
    container_name: constant_be
    build:
      context: ./backend
    image: constant/constant_be
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    depends_on:
      - mysql
